In [1]:
import numpy as np

In [9]:
# data loading
dta = np.loadtxt("hw1_train.dat", dtype=np.float, delimiter='\t')

In [10]:
dta

array([[ 1.56186, -2.54905, -1.98638, ...,  1.32496, -2.26376, -1.     ],
       [ 3.89045, -0.02852,  2.2065 , ..., -2.31854, -1.40395, -1.     ],
       [-1.85626, -1.38071, -0.0755 , ..., -2.35446, -1.43411,  1.     ],
       ...,
       [-3.8145 ,  0.89167, -2.15984, ..., -1.57172,  0.15997,  1.     ],
       [-2.11276, -1.91391, -0.63889, ..., -3.45234, -1.29036,  1.     ],
       [-2.50787, -1.02966,  0.5274 , ...,  1.14198,  0.64107, -1.     ]])

In [11]:
np.shape(dta)

(100, 11)

In [23]:
dta_n = len(dta)
dta_n

100

# PL Algorithm

In [87]:
def signf(value):
    return 1 if value > 0 else -1

## On-paper implementation

Residual may be large...

In [157]:
def PLAEXP(x, y):
    
    #inquirements
    update = [] #for 16, 18, 19, 20
    w0 = [] #for 17
    res = [] #insterests
    
    for exp in range(10000):
        #initialize parameters
        w = np.zeros(11) #for 16: 11
        updatetemp = 0
        maxcorrect = 0
        
        #PLA
        while maxcorrect < 500: #stop-critria
            current_index = np.random.randint(0, dta_n-1) #randomly pick a example
            if y[current_index] != signf(x[current_index, :].dot(w)):
                w += y[current_index] * x[current_index, :]
                updatetemp += 1
                maxcorrect = 0
            else:
                maxcorrect += 1
        
        #records
        update.append(updatetemp)
        w0.append(w[0])
        
        #calculus of res
        restemp = 0
        for i in range(100):
            restemp += abs(y[i] - signf(x[i, :].dot(w)))
        res.append(restemp)

    print("median of # of updates is", np.median(update),"median of w0", np.median(w0))
    print(np.mean(res))

## Residual = 0 implementation

In [122]:
def PLAEXP_NEW(x, y):
    
    #inquirements
    update = [] #for 16, 18, 19, 20
    w0 = [] #for 17
    res = [] #insterests
    
    for exp in range(1000):
        #initialize parameters
        w = np.zeros(11) #for 16: 11
        updatetemp = 0
        maxcorrect = 0
        
        #PLA
        while True:
            restemp = 0
            for i in range(100):
                if y[i] != signf(x[i, :].dot(w)):
                    w += y[i] * x[i, :]
                    updatetemp += 1
                    restemp += 1
            if restemp == 0: #stop-critria: all-right
                break
        
        #records
        update.append(updatetemp)
        w0.append(w[0])
        
        #calculus of res
        restemp = 0
        for i in range(100):
            restemp += abs(y[i] - signf(x[i, :].dot(w)))
        res.append(restemp)

    print("median of # of updates is", np.median(update),"median of w0", np.median(w0))
    print(np.mean(res))

# 16 & 17

In [158]:
x = np.concatenate((np.ones((dta_n,1)), dta[:, 0:10]), axis=1)
x

array([[ 1.     ,  1.56186, -2.54905, ..., -0.30951,  1.32496, -2.26376],
       [ 1.     ,  3.89045, -0.02852, ..., -1.30547, -2.31854, -1.40395],
       [ 1.     , -1.85626, -1.38071, ..., -1.11643, -2.35446, -1.43411],
       ...,
       [ 1.     , -3.8145 ,  0.89167, ...,  0.45259, -1.57172,  0.15997],
       [ 1.     , -2.11276, -1.91391, ...,  2.756  , -3.45234, -1.29036],
       [ 1.     , -2.50787, -1.02966, ..., -0.31516,  1.14198,  0.64107]])

In [159]:
y = dta[:, 10]
y

array([-1., -1.,  1.,  1.,  1.,  1., -1., -1., -1., -1., -1.,  1., -1.,
        1.,  1.,  1., -1., -1., -1.,  1.,  1., -1.,  1., -1., -1.,  1.,
        1.,  1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,
       -1., -1.,  1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        1., -1.,  1., -1.,  1.,  1., -1.,  1., -1.,  1., -1.,  1.,  1.,
        1.,  1., -1., -1.,  1., -1., -1.,  1.,  1., -1.,  1., -1.,  1.,
        1., -1., -1.,  1.,  1., -1., -1.,  1., -1.,  1., -1., -1.,  1.,
        1., -1.,  1.,  1., -1., -1.,  1.,  1., -1.])

In [160]:
PLAEXP(x, y)

median of # of updates is 11.0 median of w0 -7.0
0.0162


In [133]:
PLAEXP_NEW(x, y)

median of # of updates is 14.0 median of w0 0.0
0.0


# 18

In [161]:
x = np.concatenate((np.ones((dta_n,1))*10, dta[:, 0:10]), axis=1)
x

array([[10.     ,  1.56186, -2.54905, ..., -0.30951,  1.32496, -2.26376],
       [10.     ,  3.89045, -0.02852, ..., -1.30547, -2.31854, -1.40395],
       [10.     , -1.85626, -1.38071, ..., -1.11643, -2.35446, -1.43411],
       ...,
       [10.     , -3.8145 ,  0.89167, ...,  0.45259, -1.57172,  0.15997],
       [10.     , -2.11276, -1.91391, ...,  2.756  , -3.45234, -1.29036],
       [10.     , -2.50787, -1.02966, ..., -0.31516,  1.14198,  0.64107]])

In [162]:
y = dta[:, 10]
y

array([-1., -1.,  1.,  1.,  1.,  1., -1., -1., -1., -1., -1.,  1., -1.,
        1.,  1.,  1., -1., -1., -1.,  1.,  1., -1.,  1., -1., -1.,  1.,
        1.,  1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,
       -1., -1.,  1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        1., -1.,  1., -1.,  1.,  1., -1.,  1., -1.,  1., -1.,  1.,  1.,
        1.,  1., -1., -1.,  1., -1., -1.,  1.,  1., -1.,  1., -1.,  1.,
        1., -1., -1.,  1.,  1., -1., -1.,  1., -1.,  1., -1., -1.,  1.,
        1., -1.,  1.,  1., -1., -1.,  1.,  1., -1.])

In [163]:
PLAEXP(x, y)

median of # of updates is 15.0 median of w0 0.0
0.0126


In [130]:
PLAEXP_NEW(x, y)

median of # of updates is 14.0 median of w0 0.0
0.0


# 19

In [164]:
x = np.concatenate((np.ones((dta_n,1))*0, dta[:, 0:10]), axis=1)
x

array([[ 0.     ,  1.56186, -2.54905, ..., -0.30951,  1.32496, -2.26376],
       [ 0.     ,  3.89045, -0.02852, ..., -1.30547, -2.31854, -1.40395],
       [ 0.     , -1.85626, -1.38071, ..., -1.11643, -2.35446, -1.43411],
       ...,
       [ 0.     , -3.8145 ,  0.89167, ...,  0.45259, -1.57172,  0.15997],
       [ 0.     , -2.11276, -1.91391, ...,  2.756  , -3.45234, -1.29036],
       [ 0.     , -2.50787, -1.02966, ..., -0.31516,  1.14198,  0.64107]])

In [165]:
y = dta[:, 10]
y

array([-1., -1.,  1.,  1.,  1.,  1., -1., -1., -1., -1., -1.,  1., -1.,
        1.,  1.,  1., -1., -1., -1.,  1.,  1., -1.,  1., -1., -1.,  1.,
        1.,  1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,
       -1., -1.,  1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        1., -1.,  1., -1.,  1.,  1., -1.,  1., -1.,  1., -1.,  1.,  1.,
        1.,  1., -1., -1.,  1., -1., -1.,  1.,  1., -1.,  1., -1.,  1.,
        1., -1., -1.,  1.,  1., -1., -1.,  1., -1.,  1., -1., -1.,  1.,
        1., -1.,  1.,  1., -1., -1.,  1.,  1., -1.])

In [166]:
PLAEXP(x, y)

median of # of updates is 17.0 median of w0 0.0
0.0224


In [142]:
PLAEXP_NEW(x, y)

median of # of updates is 15.0 median of w0 0.0
0.0


# 20

In [167]:
x = np.concatenate((np.ones((dta_n,1))*0, dta[:, 0:10]), axis=1)/4
x

array([[ 0.       ,  0.390465 , -0.6372625, ..., -0.0773775,  0.33124  ,
        -0.56594  ],
       [ 0.       ,  0.9726125, -0.00713  , ..., -0.3263675, -0.579635 ,
        -0.3509875],
       [ 0.       , -0.464065 , -0.3451775, ..., -0.2791075, -0.588615 ,
        -0.3585275],
       ...,
       [ 0.       , -0.953625 ,  0.2229175, ...,  0.1131475, -0.39293  ,
         0.0399925],
       [ 0.       , -0.52819  , -0.4784775, ...,  0.689    , -0.863085 ,
        -0.32259  ],
       [ 0.       , -0.6269675, -0.257415 , ..., -0.07879  ,  0.285495 ,
         0.1602675]])

In [168]:
y = dta[:, 10]
y

array([-1., -1.,  1.,  1.,  1.,  1., -1., -1., -1., -1., -1.,  1., -1.,
        1.,  1.,  1., -1., -1., -1.,  1.,  1., -1.,  1., -1., -1.,  1.,
        1.,  1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,
       -1., -1.,  1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        1., -1.,  1., -1.,  1.,  1., -1.,  1., -1.,  1., -1.,  1.,  1.,
        1.,  1., -1., -1.,  1., -1., -1.,  1.,  1., -1.,  1., -1.,  1.,
        1., -1., -1.,  1.,  1., -1., -1.,  1., -1.,  1., -1., -1.,  1.,
        1., -1.,  1.,  1., -1., -1.,  1.,  1., -1.])

In [169]:
PLAEXP(x, y)

median of # of updates is 17.0 median of w0 0.0
0.0204


In [154]:
PLAEXP_NEW(x, y)

median of # of updates is 15.0 median of w0 0.0
0.0
