In [47]:
import numpy as np
import numpy.linalg as la

In [48]:
# data loading
train = np.loadtxt("hw3_train.dat", dtype=np.float, delimiter='\t')
train

array([[ 2.965153,  2.447427,  1.958754, ..., -4.510862, -0.006392,
        -1.      ],
       [-4.303194, -0.032933,  2.568076, ..., -0.949456, -0.744622,
        -1.      ],
       [-0.261568,  0.974854, -1.132005, ...,  2.728657,  4.001672,
        -1.      ],
       ...,
       [-3.106073, -0.425107, -4.141368, ..., -1.741274,  1.479998,
        -1.      ],
       [ 3.665836,  3.401544, -0.779725, ...,  2.058829,  1.474205,
         1.      ],
       [ 1.74612 ,  2.365236, -2.501292, ...,  3.269879, -0.259019,
         1.      ]])

In [50]:
np.shape(train)

(1000, 11)

In [49]:
test = np.loadtxt("hw3_test.dat", dtype=np.float, delimiter='\t')
test

array([[ 1.406809,  1.629765,  0.137603, ..., -0.019709,  0.200252,
         1.      ],
       [-4.507169, -0.944514, -1.634057, ...,  3.074277,  1.056912,
         1.      ],
       [-1.559574, -4.985006,  0.946881, ...,  2.908434,  0.312697,
        -1.      ],
       ...,
       [-1.019819,  0.524448,  0.617346, ...,  1.389058,  1.085457,
         1.      ],
       [ 1.42676 , -1.123184,  1.323768, ..., -3.147399, -1.061905,
        -1.      ],
       [-1.098224,  3.060828,  0.935526, ...,  0.476239, -4.390546,
         1.      ]])

# Q 14

The answer is 0.60. [d]

In [72]:
# data
x = np.concatenate((np.ones((1000,1)), train[:, 0:10]), axis=1)
x

array([[ 1.      ,  2.965153,  2.447427, ...,  1.621895, -4.510862,
        -0.006392],
       [ 1.      , -4.303194, -0.032933, ..., -4.560341, -0.949456,
        -0.744622],
       [ 1.      , -0.261568,  0.974854, ..., -4.031803,  2.728657,
         4.001672],
       ...,
       [ 1.      , -3.106073, -0.425107, ..., -2.093555, -1.741274,
         1.479998],
       [ 1.      ,  3.665836,  3.401544, ...,  0.78021 ,  2.058829,
         1.474205],
       [ 1.      ,  1.74612 ,  2.365236, ..., -0.833364,  3.269879,
        -0.259019]])

In [73]:
y = train[:, 10]
y

array([-1., -1., -1.,  1., -1.,  1., -1.,  1., -1., -1.,  1.,  1., -1.,
        1., -1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,
       -1.,  1., -1., -1., -1., -1.,  1., -1.,  1.,  1.,  1., -1., -1.,
       -1.,  1., -1.,  1.,  1.,  1.,  1., -1., -1., -1.,  1.,  1.,  1.,
        1.,  1., -1., -1.,  1., -1., -1., -1.,  1., -1.,  1., -1., -1.,
       -1.,  1.,  1., -1., -1.,  1.,  1.,  1., -1., -1.,  1.,  1., -1.,
        1., -1.,  1., -1.,  1., -1.,  1.,  1., -1.,  1., -1.,  1.,  1.,
        1., -1., -1., -1., -1.,  1., -1.,  1., -1.,  1.,  1.,  1., -1.,
       -1.,  1., -1.,  1., -1., -1.,  1.,  1., -1., -1.,  1.,  1., -1.,
        1.,  1., -1.,  1.,  1., -1., -1.,  1.,  1., -1.,  1.,  1.,  1.,
        1.,  1., -1., -1., -1.,  1., -1., -1., -1.,  1.,  1.,  1., -1.,
        1., -1.,  1., -1.,  1., -1.,  1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1.,  1., -1., -1., -1.,  1.,  1., -1., -1., -1.,  1.,
       -1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1., -1., -1

In [74]:
w_lin = la.solve(x.T@x, x.T@y)
w_lin

array([ 0.00754448,  0.14325775,  0.03548979,  0.02775754,  0.02547401,
       -0.08173504,  0.0807915 , -0.10929449,  0.07789522,  0.16407524,
        0.14069183])

In [84]:
ein_lin = 0.001*(la.norm(x@w_lin-y)**2)
ein_lin

0.6053223804672918

In [76]:
# gradient
nablaein_lin = 0.002*(x.T@x@w_lin-x.T@y)
nablaein_lin

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  2.84217094e-17,
        2.84217094e-17,  0.00000000e+00,  0.00000000e+00, -2.27373675e-16,
       -1.13686838e-16,  0.00000000e+00, -2.27373675e-16])

# Q15

The answer is 1800 [c].

In [88]:
def exp(w,x,y):
    count = 0
    while 0.001*(la.norm(x@w-y)**2) > 1.01*ein_lin:
        #randomly pick example
        tempidx = np.random.randint(0, 999)
        xt = x[tempidx]
        yt = y[tempidx]
        #SGD update
        w = w+0.001*2*(yt-w.T@xt)*xt
        #count iterations
        count+=1
    return count

In [89]:
x = np.concatenate((np.ones((1000,1)), train[:, 0:10]), axis=1)
y = train[:, 10]
w = np.zeros(11)
n_iter = []
for i in range(1000):
    n_iter.append(exp(w,x,y))
np.mean(n_iter)

1871.06

# Q16

The answer is 0.56 [c].

In [90]:
def sigmoid(x): 
    s = 1 / (1 + np.exp(-x))
    return s

In [91]:
def exp16(w,x,y):
    for i in range(500):
        #randomly pick example
        tempidx = np.random.randint(0, 999)
        xt = x[tempidx]
        yt = y[tempidx]
        #SGD update
        w = w+0.001*sigmoid(-yt*(w.T@xt))*yt*xt
        #count iterations
    ein_ce = 0
    for i in range(1000):
        ein_ce += np.log(1+np.exp(-y[i]*(w.T@x[i])))
    ein_ce /= 1000
    return ein_ce

In [96]:
x = np.concatenate((np.ones((1000,1)), train[:, 0:10]), axis=1)
y = train[:, 10]
w = np.zeros(11)
all_ce = []
for i in range(1000):
    all_ce.append(exp16(w,x,y))
np.mean(all_ce)

0.5691906286766145

# Q17

The answer is 0.50 [b].

In [97]:
x = np.concatenate((np.ones((1000,1)), train[:, 0:10]), axis=1)
y = train[:, 10]
w = w_lin
all_ce = []
for i in range(1000):
    all_ce.append(exp16(w,x,y))
np.mean(all_ce)

0.5028703930285623

# Q18
The answer is 0.32 [a].

In [99]:
def sign(x):
    return 1 if x > 0 else -1

In [102]:
train_x = np.concatenate((np.ones((1000,1)), train[:, 0:10]), axis=1)
train_y = train[:, 10]
test_x = np.concatenate((np.ones((3000,1)), test[:, 0:10]), axis=1)
test_y = test[:, 10]

In [103]:
ein10 = np.mean([(1-sign(w_lin.T@train_x[i])*train_y[i])/2 for i in range(1000)])
eout10 = np.mean([(1-sign(w_lin.T@test_x[i])*test_y[i])/2 for i in range(3000)])
abs(ein10-eout10)

0.3226666666666666

# Q19
The answer is 0.36 [b]

In [114]:
train_x_19 = np.ones((1000,1))
test_x_19 = np.ones((3000,1))
for i in range(3):
    train_x_19 = np.concatenate((train_x_19, train[:, 0:10]**(i+1)), axis=1)
    test_x_19 = np.concatenate((test_x_19, test[:, 0:10]**(i+1)), axis=1)

In [116]:
np.shape(train_x_19)

(1000, 31)

In [117]:
np.shape(test_x_19)

(3000, 31)

In [118]:
w_lin19 = la.solve(train_x_19.T@train_x_19, train_x_19.T@train_y)
ein10 = np.mean([(1-sign(w_lin19.T@train_x_19[i])*train_y[i])/2 for i in range(1000)])
eout10 = np.mean([(1-sign(w_lin19.T@test_x_19[i])*test_y[i])/2 for i in range(3000)])
abs(ein10-eout10)

0.37366666666666665

# Q20
The answer is 0.44 [d]

In [119]:
train_x_20 = np.ones((1000,1))
test_x_20 = np.ones((3000,1))
for i in range(10):
    train_x_20 = np.concatenate((train_x_20, train[:, 0:10]**(i+1)), axis=1)
    test_x_20 = np.concatenate((test_x_20, test[:, 0:10]**(i+1)), axis=1)
w_lin20 = la.solve(train_x_20.T@train_x_20, train_x_20.T@train_y)
ein10 = np.mean([(1-sign(w_lin20.T@train_x_20[i])*train_y[i])/2 for i in range(1000)])
eout10 = np.mean([(1-sign(w_lin20.T@test_x_20[i])*test_y[i])/2 for i in range(3000)])
abs(ein10-eout10)

0.44666666666666666

In [120]:
np.shape(test_x_20)

(3000, 101)